- src/main/java/io/kestra/plugin/dbt/cli/AbstractDbt.java
- src/main/java/io/kestra/plugin/dbt/cli/AbstractRun.java
As it is no more allowed to add it before the command since DBT 1.5.
Fixes #30
> fix: add --profiles-dir option after the command

- src/main/java/io/kestra/plugin/dbt/cli/DbtCLI.java
> feat: dbt CLI projectDir

- dockerfiles/dbt-clickhouse.Dockerfile
> feat: clickhouse adapter

- src/main/java/io/kestra/plugin/dbt/cloud/TriggerRun.java
Fixes https://github.com/kestra-io/plugin-dbt/issues/54
> Allow user to setup poll frequency

- src/main/java/io/kestra/plugin/dbt/cloud/TriggerRun.java
Fixes https://github.com/kestra-io/plugin-dbt/issues/55
> Streaming dbt cloud logs

- src/main/java/io/kestra/plugin/dbt/cloud/TriggerRun.java
Fixes https://github.com/kestra-io/plugin-dbt/issues/58
> fix substring index being negative

- src/main/java/io/kestra/plugin/dbt/cloud/CheckStatus.java
- src/main/java/io/kestra/plugin/dbt/cloud/TriggerRun.java
- src/test/java/io/kestra/plugin/dbt/cloud/CheckStatusTest.java
Fixes https://github.com/kestra-io/plugin-dbt/issues/62
> Create task for Status Check

- src/main/java/io/kestra/plugin/dbt/cloud/CheckStatus.java
- src/main/java/io/kestra/plugin/dbt/cloud/TriggerRun.java
- src/test/java/io/kestra/plugin/dbt/cloud/CheckStatusTest.java
> feat(tasks): decouple job status check from trigger run (#65)

- src/main/java/io/kestra/plugin/dbt/cloud/CheckStatus.java
- src/main/java/io/kestra/plugin/dbt/cloud/TriggerRun.java
- src/test/java/io/kestra/plugin/dbt/cloud/CheckStatusTest.java
Fixes https://github.com/kestra-io/plugin-dbt/issues/68
> Render runId from string for CheckStatus dbt Cloud task

- src/test/resources/flows/full.yaml
> chore: rename input id to input name

- src/main/java/io/kestra/plugin/dbt/cli/Build.java
- src/main/java/io/kestra/plugin/dbt/cli/Compile.java
- src/main/java/io/kestra/plugin/dbt/cli/DbtCLI.java
- src/main/java/io/kestra/plugin/dbt/cli/Deps.java
- src/main/java/io/kestra/plugin/dbt/cli/Freshness.java
- src/main/java/io/kestra/plugin/dbt/cli/List.java
- src/main/java/io/kestra/plugin/dbt/cli/Run.java
- src/main/java/io/kestra/plugin/dbt/cli/Seed.java
- src/main/java/io/kestra/plugin/dbt/cli/Setup.java
- src/main/java/io/kestra/plugin/dbt/cli/Snapshot.java
- src/main/java/io/kestra/plugin/dbt/cli/Test.java
- src/main/java/io/kestra/plugin/dbt/cloud/AbstractDbtCloud.java
- src/main/java/io/kestra/plugin/dbt/cloud/CheckStatus.java
- src/main/java/io/kestra/plugin/dbt/cloud/TriggerRun.java
The major correction is in dbt Deps flow example where the task type is corrected from "Debs" -> "Deps".
> fix(docs): correct the docs and examples of dbt

- build.gradle
- gradle.properties
> fix: HttpClient missing Jackson modules

- src/main/java/io/kestra/plugin/dbt/cli/AbstractDbt.java
- src/main/java/io/kestra/plugin/dbt/cli/DbtCLI.java
> feat: allow overriding the working directory profile

- src/main/java/io/kestra/plugin/dbt/cli/DbtCLI.java
- src/main/java/io/kestra/plugin/dbt/cli/Setup.java
Additional changes:
* add implementation for the new getContainerImage method
Fix: #78
> feat(cli): add support for failFast task property (#78)

- src/main/java/io/kestra/plugin/dbt/cli/DbtCLI.java
- src/test/java/io/kestra/plugin/dbt/cli/DbtCLITest.java
Fixes https://github.com/kestra-io/plugin-dbt/issues/123
> fix: projectDir should not be used to retrieve the profile

- src/main/java/io/kestra/plugin/dbt/cli/DbtCLI.java
> feat: allow overriding the profile and log an INFO

- src/main/java/io/kestra/plugin/dbt/cli/DbtCLI.java
> feat: warn on missing 'projectDIr' property

- src/main/java/io/kestra/plugin/dbt/cli/DbtCLI.java
closes https://github.com/kestra-io/plugin-dbt/issues/139
> Fix projectDir

- src/main/java/io/kestra/plugin/dbt/cli/DbtCLI.java
- src/main/java/io/kestra/plugin/dbt/cli/LogService.java
enforce json log for DbtCli plugin commands
fix log level "warning" to "warn"
#60
> fix: aggregated logs

- .github/workflows/main.yml
- src/main/java/io/kestra/plugin/dbt/cli/DbtCLI.java
- src/test/java/io/kestra/plugin/dbt/cli/BuildTest.java
- src/test/java/io/kestra/plugin/dbt/cli/DbtCLITest.java
- src/test/resources/project/models/requests.sql
> feat: add storeManifest and loadManifest

- src/main/java/io/kestra/plugin/dbt/cli/DbtCLI.java
> refactor: add doc and warning on not found manifest with loadManifest

- src/main/java/io/kestra/plugin/dbt/cli/DbtCLI.java
- src/test/java/io/kestra/plugin/dbt/cli/DbtCLITest.java
> feat(*): add output files in case of dbt specific task failure

- dockerfiles/dbt-fusion.Dockerfile
- src/main/java/io/kestra/plugin/dbt/cli/DbtCLI.java
- src/test/java/io/kestra/plugin/dbt/cli/DbtCLITest.java
> feat(cli): support for fusion CLI as engine
